api_platform:
    title: Hello API Platform
    version: 1.0.0
    enable_swagger_ui: true
    defaults:
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        json:   ['application/json']
        jsonld: ['application/ld+json']
